# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: The Veiled Garden
description: >-
  Coding, Food, Fitness, Poetry & Books
baseurl: ""       # the subpath of your site, e.g. /blog
url: ""           # the base hostname & protocol for your site, e.g. http://example.com
github_username: qrzn

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults: Set the default layout for all pages to "default"
defaults:
  - scope:
      path: ""       # Applies to all files in your site
      type: "pages"
    values:
      layout: default

exclude:
  - README.MD

collections:
  books:
    output: true
